backend:
  name: proxy
  proxy_url: http://localhost:8081/api/v1
media_folder: "src/images"
public_folder: "/images"
collections:
  - name: "homepage"
    label: "Homepage"
    files:
    - name: "index"
      label: "Index Page"
      file: "src/index.md"
      create: true
      slug: "{{slug}}"
      fields:
        - { label: "Title", name: "title", widget: "string" }
        - { label: "Body", name: "body", widget: "markdown" }
        - { label: "Hero Image", name: "hero_image", widget: "image" }
        - { label: "Bandcamp Embed",  name: "bandcamp_embed",  widget: "markdown", required: false }
        - { label: "Contact Form",  name: "contact_form",  widget: "markdown", required: false }
  - name: "pages"
    label: "Pages"
    folder: "src/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Permalink", name: "permalink", widget: "string", required: false, hint: "Set to /gallery/ if you want this to be the gallery page" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Hero Image", name: "hero_image", widget: "image" }
      - { label: "Bandcamp Embed",  name: "bandcamp_embed",  widget: "text", required: false }
  - name: "projects"
    label: "Projects"
    folder: "src/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "base.njk" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "news"
    label: "News"
    folder: "src/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    sort: "date:desc"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "base.njk" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Featured Image", name: "image", widget: "image", required: false }
